### ISSUE TITLE
Add support for Managed Identity

### ISSUE THREAD

**Issue by cruscio** [caddy-dns/azure#6]
Would it be possible to add support for Managed Identity authentication to Azure DNS? 

Instead of providing `client_id` and `client_secret` for a service principal, the configuration would include a `managed_identity` property that could be either `System` or the Client ID of a user-assigned managed identity. Caddy could then use the instance metadata service to get a bearer token, and then use that token to configure Azure DNS. 

Ideally this would support both the cloud [instance metadata service](https://learn.microsoft.com/en-us/azure/virtual-machines/instance-metadata-service) and the Arc agent [identity service](https://learn.microsoft.com/en-us/azure/azure-arc/servers/managed-identity-authentication)

**Comment by cruscio** [comment]
Looks like this uses [libdns/azure](https://github.com/caddy-dns/azure/blob/fffcc1fc33cfa734be33a2b904bd269b643359cd/azure.go#L4) and that uses [azure/azure-sdk-for-go/sdk/azidentity](https://github.com/libdns/azure/blob/32d742612525d77e7456f36f4233856ffd566a0c/client.go#L12), and azidentity supports [managed identity](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/README.md#managed-identity).

**Comment by kurokobo** [comment]
@cruscio 
Thanks for filling the issue 😃 
Yes, technically, it is possible to support managed identity authentication. The reason it is not implemented now is simply that I did not have that requirement.

I can't guarantee any ETA, but I will try to find time to work on it. Of course, contributions are welcome 👍

**Comment by kurokobo** [comment]
@cruscio 
Hi, apoligies for my long delay. Now I've just released new `dns.providers.azure` v0.5.0 and confirmed that authentication using managed identity works as expected on both Azure VM and Azure Arc connected machine.

Simply removing all of `tenant_id`, `client_id`, `client_secret` switches to use managed identity instead of service principal.
Try it by building your caddy with v0.5.0 of `dns.providers.azure` 😄 

Thank you again for requesting new feature!
